#!/usr/bin/env bash
# make_manifest.sh — SHA-256 every material evidence + source file into
# evidence/manifest.json so each numerical claim is anchored to a hashed artifact.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; cd "$ROOT"
OUT=evidence/manifest.json
{
  echo "{"
  echo "  \"project\": \"project2_cxl_validation\","
  echo "  \"note\": \"SHA-256 of project-owned SOURCES (RTL, TB, model, scripts, formal, docs). Evidence logs in evidence/raw are regenerated by make and are git-ignored, so hashing sources keeps the manifest stable and path-independent.\","
  echo "  \"files\": ["
  first=1
  while IFS= read -r f; do
    h=$(sha256sum "$f" | cut -d' ' -f1)
    [ $first -eq 0 ] && echo ","
    first=0
    printf '    {"path": "%s", "sha256": "%s"}' "$f" "$h"
  done < <(find rtl tb/models tb/sv formal scripts docs -type f \( -name '*.sv' -o -name '*.py' -o -name '*.sh' -o -name '*.sby' -o -name '*.md' \) | sort)
  echo ""
  echo "  ]"
  echo "}"
} > "$OUT"
echo "wrote $OUT ($(grep -c sha256 "$OUT") files hashed)"
